# Generated by Django 4.0.2 on 2022-02-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvimportdemo', '0002_employee_delete_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employees',
        ),
    ]
