# Generated by Django 4.0.2 on 2022-02-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvimportdemo', '0003_rename_employee_employees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'ordering': ['first_name']},
        ),
    ]
